export const turnFixture = {
  timelineName: "无王航线",
  chapter: 1,
  chapterName: "历史现场",
  protagonistName: "沈砚",
  protagonistAge: 24,
  lifeStage: "命运当日",
  yearLabel: "208 年冬",
  location: "长江赤壁水域",
  role: "周瑜帐下负责火船的军需官",
  immediateObjective: "在曹军识破诈降前决定火船启航时机",
  timePressure: "距离曹军发现火船约半个时辰",
  headline: "东南风还没有来",
  narrative: "黄盖已经登船，曹军的巡哨却比预期更近。你握着发船铜令，任何迟疑都可能让火攻提前暴露。",
  baselineAnchor: "孙刘联军最终借东风火攻曹操水军。",
  historicalAnchors: ["周瑜", "黄盖诈降", "曹操连环船"],
  rippleLens: "origin",
  causalBridge: "你手中的发船铜令将决定火攻是否进入正史",
  turningPointStakes: "这道军令将决定孙刘联盟能否保住长江防线",
  worldStateChange: "火船启航规则已经被你改写",
  divergenceProof: "真实历史等待东风，当前线改由你的铜令决定火攻时机",
  previousEcho: null,
  choices: [
    {
      id: "A",
      label: "立刻放出第一批火船",
      intent: "抢在曹军巡哨靠近前点火",
      deviationClass: "nudge",
      usesTravelerStrength: false,
      actionSpec: { actor: "你与黄盖", action: "点燃前列十艘蒙冲", target: "曹军连环船左翼", deadline: "巡哨抵近前半刻" },
      instantEcho: {
        directResult: "曹军左翼提前起火",
        unexpectedCost: "前列火船更易被截",
        beneficiary: "孙刘前锋",
        payer: "先发火船水手",
      },
    },
    {
      id: "B",
      label: "用旗语诱使巡哨让航",
      intent: "伪造曹军旗号为火船开路",
      deviationClass: "reform",
      usesTravelerStrength: true,
      actionSpec: { actor: "你与旗手", action: "伪造曹军粮船旗语", target: "江面巡哨舰", deadline: "两轮旗号之内" },
      instantEcho: {
        directResult: "曹军巡哨让出水道",
        unexpectedCost: "伪旗语暴露后难再使用",
        beneficiary: "黄盖火船队",
        payer: "执行旗语的哨兵",
      },
    },
    {
      id: "C",
      label: "扣住黄盖改袭乌林粮仓",
      intent: "放弃连环船，先烧曹军军粮",
      deviationClass: "rupture",
      usesTravelerStrength: false,
      actionSpec: { actor: "你与火船队", action: "转舵突袭并焚烧", target: "乌林岸上曹军粮仓", deadline: "东南风转向之前" },
      instantEcho: {
        directResult: "乌林粮仓先于水寨燃烧",
        unexpectedCost: "曹军主力得以离船整队",
        beneficiary: "截断粮道的江东军",
        payer: "放弃正面火攻的联军",
      },
    },
  ],
  metrics: { stability: 45, prosperity: 52, freedom: 31, cost: 18 },
  metricDeltas: { stability: 4, prosperity: 2, freedom: -3, cost: 5 },
  causalLedger: [
    { fact: "火船被提前放出", causedByChapter: 1, mustAffect: "曹军左翼与撤退路线" },
  ],
  callbackUsed: null,
  visualTone: "ancient",
  memorySummary: "火船提前出发，曹军左翼在主攻前已经起火。",
} as const;

export const endingFixture = {
  worldName: "公议纪元",
  frontPageHeadline: "跨洲公议院通过第两千份城市自治章程",
  protagonistName: "沈砚",
  lifespanSummary: "沈砚从赤壁军需官走到公议制度的奠基者，一生十二次把个人选择写进公共秩序。",
  deathScene: {
    yearLabel: "254 年冬",
    age: 70,
    place: "江夏公议院旧址",
    finalMoment: "沈砚听完最后一项表决结果，在晨钟响起时闭上眼睛。",
    lastingLegacy: "他留下的不是王位，而是一套任何城市都能质询权力的议事规则。",
  },
  historyTimeline: Array.from({ length: 12 }, (_, index) => ({
    chapter: index + 1,
    yearLabel: `${index + 1}纪元`,
    playerChoice: `选择${index + 1}`,
    consequence: `后果${index + 1}`,
  })),
  causalChains: [
    { origin: "公开遗诏", transformation: "摄政议会", payoff: "城市自治" },
    { origin: "共享道路", transformation: "跨洲税制", payoff: "公共交通" },
    { origin: "承认地方语言", transformation: "多语教育", payoff: "翻译网络" },
  ],
  ordinaryLife2026: ["通勤者使用公共驿路", "家庭持有多语身份证", "学校教授城市议事"],
  posthumousChronicle: [
    { period: "他死后十年", title: "继承者争夺解释权", narrative: "旧部把他的手稿拆成互相冲突的制度版本。", inheritedChange: "公开质询仍成为所有派系都不敢废除的底线。" },
    { period: "他死后一百年", title: "城市把规则写进石碑", narrative: "商路沿线开始复制公议程序。", inheritedChange: "地方税与战争动员必须公开表决。" },
    { period: "工业时代", title: "机器进入公议院", narrative: "新工业放大财富，也迫使劳动者要求席位。", inheritedChange: "技术许可与工人代表成为同一套制度。" },
    { period: "2026 年", title: "陌生人仍在使用他的遗产", narrative: "没有人能完整复述沈砚的一生，但每个人都活在他的选择之后。", inheritedChange: "权力必须留下可供普通人追问的记录。" },
  ],
  closingPassage: "沈砚没有看见 2026 年。那一年，人们仍在争论他的制度，却已无法想象一个决定不必留下回执的世界。",
  greatestGain: "地方自治成为默认制度",
  hiddenPrice: "跨洲协调极其缓慢",
  strangestDetail: "婚礼要交换城市通行章",
  biggestBeneficiary: "自治城市居民",
  biggestLoser: "世袭总督",
  rewriteLevel: "大陆改写",
  plausibilityScore: 78,
  plausibilityReason: "制度变化沿既有道路与继承危机扩散。",
  shareLine: "我让帝国没有立刻分裂，却创造了一个由城市投票的2026。",
};
