export const turnFixture = {
  timelineName: "无王航线",
  chapter: 1,
  chapterName: "历史现场",
  yearLabel: "208 年冬",
  location: "长江赤壁水域",
  role: "周瑜帐下负责火船的军需官",
  immediateObjective: "在曹军识破诈降前决定火船启航时机",
  timePressure: "距离曹军发现火船约半个时辰",
  headline: "东南风还没有来",
  narrative: "黄盖已经登船，曹军的巡哨却比预期更近。你握着发船铜令，任何迟疑都可能让火攻提前暴露。",
  baselineAnchor: "孙刘联军最终借东风火攻曹操水军。",
  rippleLens: "origin",
  causalBridge: "你手中的发船铜令将决定火攻是否进入正史",
  turningPointStakes: "这道军令将决定孙刘联盟能否保住长江防线",
  worldStateChange: "火船启航规则已经被你改写",
  divergenceProof: "真实历史等待东风，当前线改由你的铜令决定火攻时机",
  previousEcho: null,
  choices: [
    {
      id: "A",
      label: "公开完整遗诏",
      intent: "用透明换取短暂团结",
      deviationClass: "nudge",
      instantEcho: {
        directResult: "继业者暂停争夺",
        unexpectedCost: "地方军团开始索要表决权",
        beneficiary: "城市书记官",
        payer: "世袭将领",
      },
    },
    {
      id: "B",
      label: "扶植年幼继承人",
      intent: "保住王朝名义",
      deviationClass: "reform",
      instantEcho: {
        directResult: "摄政制度被正式确立",
        unexpectedCost: "宫廷派系掌握幼主",
        beneficiary: "摄政官",
        payer: "边疆总督",
      },
    },
    {
      id: "C",
      label: "承认各地自治",
      intent: "用分权避免内战",
      deviationClass: "rupture",
      instantEcho: {
        directResult: "各行省停止进军巴比伦",
        unexpectedCost: "统一税制当场失效",
        beneficiary: "地方议会",
        payer: "帝国军需官",
      },
    },
  ],
  metrics: { stability: 45, prosperity: 52, freedom: 31, cost: 18 },
  metricDeltas: { stability: 4, prosperity: 2, freedom: -3, cost: 5 },
  causalLedger: [
    { fact: "完整遗诏被公开", causedByChapter: 1, mustAffect: "继业者的合法性" },
  ],
  callbackUsed: null,
  visualTone: "ancient",
  memorySummary: "遗诏公开后，继业者接受了暂时共同摄政。",
} as const;

export const endingFixture = {
  worldName: "公议纪元",
  frontPageHeadline: "跨洲公议院通过第两千份城市自治章程",
  historyTimeline: Array.from({ length: 11 }, (_, index) => ({
    chapter: index + 1,
    yearLabel: `${index + 1}纪元`,
    playerChoice: `选择${index + 1}`,
    consequence: `后果${index + 1}`,
  })),
  causalChains: [
    { origin: "公开遗诏", transformation: "摄政议会", payoff: "城市自治" },
    { origin: "共享道路", transformation: "跨洲税制", payoff: "公共交通" },
    { origin: "承认地方语言", transformation: "多语教育", payoff: "翻译网络" },
  ],
  ordinaryLife2026: ["通勤者使用公共驿路", "家庭持有多语身份证", "学校教授城市议事"],
  greatestGain: "地方自治成为默认制度",
  hiddenPrice: "跨洲协调极其缓慢",
  strangestDetail: "婚礼要交换城市通行章",
  biggestBeneficiary: "自治城市居民",
  biggestLoser: "世袭总督",
  rewriteLevel: "大陆改写",
  plausibilityScore: 78,
  plausibilityReason: "制度变化沿既有道路与继承危机扩散。",
  shareLine: "我让帝国没有立刻分裂，却创造了一个由城市投票的2026。",
};
